// <auto-generated />
namespace DriveTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _25032018 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_25032018));
        
        string IMigrationMetadata.Id
        {
            get { return "201803251648062_25.03.2018"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
