// <auto-generated />
namespace DriveTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _25032018V : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_25032018V));
        
        string IMigrationMetadata.Id
        {
            get { return "201803251724524_25.03.2018V@"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
