// <auto-generated />
namespace DriveTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _28032018V9 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_28032018V9));
        
        string IMigrationMetadata.Id
        {
            get { return "201803281648467_28.03.2018V9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
